### PR TITLE
Log diskspace usage per core

### PR DESCRIPTION
**Pull request by HDegroote**

### CODE REVIEW

**Comment by mafintosh** [comment]
lgtm, will let @LuKks review

**Comment by LuKks** [comment]
Side note, later we could upgrade this like when the core is not fully synced then we show the core storage info (it's just four fs.stat), and when it's fully synced then we switch back to `core.byteLength` (cheap metadata)

But maybe it's a feature to show always the entire core size ha

**Comment by mafintosh** [comment]
Agreed that showing actual size also is good

**Comment by mafintosh** [comment]
ie just add all the storage info together

**Pull request merged**
